### ISSUE TITLE
Cant move items to equip slots

### ISSUE THREAD

**Issue by RickWillcox** [RickWillcox/Ender-Woods-Client#12] opened 2021-11-02 13:37 UTC
as shown in gif, I cant move items to the equip slots. the rest seems to work fin

https://user-images.githubusercontent.com/53924507/139857479-e60e6ba5-90f9-42df-a50b-3b58e2a524e5.mp4

e.

**Comment by bpodrygajlo** [comment] 2021-11-02 14:20
I think the issue is with repository versions. I'm willing to bet that one of the servers is reporting an attempt to call an RPC with incorrect number of parameters. Make sure you use the newest versions of Auth, World and Client. Also run the SQL query in Auth before running anything. I've tested this again locally and here are the results
![test12](https://user-images.githubusercontent.com/16952886/139865315-177f776f-45c1-413a-9d01-b7e164bb10ff.gif)
:

**Comment by RickWillcox** [comment] 2021-11-04 06:36
@bpodrygajlo this issue is still persisting.

**Comment by bpodrygajlo** [comment] 2021-11-04 11:30
Was an issue with item database, fixed by executing the sql in Auth.

**Closed by bpodrygajlo** 2021-11-04 11:30 UTC
